#!/usr/bin/env zsh
# Pushes apps-script/ to the template's bound Apps Script project and (re)deploys
# it as the public web app that serves the email-look "View in browser" pages.
# First run also creates the private "Newsletter web" snapshot folder.
# Issues already copied from the template keep their own copy of the script.
set -euo pipefail
cd "${0:A:h}/.."
ENV_FILE=.deploy.env
source $ENV_FILE
: ${SCRIPT_ID:?SCRIPT_ID missing from $ENV_FILE - run scripts/create-template.zsh first}
: ${FOLDER_ID:?FOLDER_ID missing from $ENV_FILE}

# Runs gws; on failure prints the API error and exits (set -e alone is silent inside $(...)).
gj() {
  local out
  if ! out=$(gws "$@" 2>/dev/null); then
    print -u2 -- "gws $1 $2 $3 failed: $(print -r -- $out | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{console.log(JSON.parse(s).error.message)}catch{console.log(s)}})')"
    [[ $* == *deployments* ]] && print -u2 "Deployments need the https://www.googleapis.com/auth/script.deployments scope (gws auth login --scopes ...)."
    exit 1
  fi
  print -r -- $out
}
# Prints a (dot-separated) field of the JSON on stdin; fails on API errors.
field() { node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const o=JSON.parse(s||"{}");if(o.error){console.error(o.error.message);process.exit(1)}let v=o;for(const k of process.argv[1].split("."))v=v==null?v:v[k];console.log(v??"")})' "$1"; }
save() { sed -i '' "/^$1=/d" $ENV_FILE; print -r -- "$1=${(P)1}" >> $ENV_FILE; }

if [[ -z ${SNAPSHOT_FOLDER_ID:-} ]]; then
  SNAPSHOT_FOLDER_ID=$(gj drive files create --params '{"fields":"id"}' \
    --json "{\"name\":\"Newsletter web\",\"mimeType\":\"application/vnd.google-apps.folder\",\"parents\":[\"$FOLDER_ID\"]}" | field id)
  save SNAPSHOT_FOLDER_ID; print "Snapshot folder: $SNAPSHOT_FOLDER_ID"
fi

write_deployment() {
  cat > apps-script/Deployment.js <<EOF
// Generated by scripts/deploy-script.zsh - do not edit.
var NEWSLETTER_DEPLOYMENT = {
  webAppUrl: '${WEB_APP_URL:-}',
  snapshotFolderId: '$SNAPSHOT_FOLDER_ID'
};
EOF
}

push() {
  gj script +push --script "$SCRIPT_ID" --dir apps-script | field files.length >/dev/null
}

new_version() {
  gj script projects versions create --params "{\"scriptId\":\"$SCRIPT_ID\"}" \
    --json "{\"description\":\"$1\"}" | field versionNumber
}

write_deployment
push
print "Pushed apps-script/ to $SCRIPT_ID"

if [[ -z ${WEB_APP_ID:-} ]]; then
  VERSION=$(new_version "Initial web app")
  DEPLOY_JSON=$(gj script projects deployments create --params "{\"scriptId\":\"$SCRIPT_ID\"}" \
    --json "{\"versionNumber\":$VERSION,\"manifestFileName\":\"appsscript\",\"description\":\"Newsletter web version\"}")
  WEB_APP_ID=$(print -r -- $DEPLOY_JSON | field deploymentId)
  WEB_APP_URL=$(print -r -- $DEPLOY_JSON | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const e=(JSON.parse(s).entryPoints||[]).find(p=>p.webApp);console.log(e?e.webApp.url:"")})')
  [[ -n $WEB_APP_URL ]] || WEB_APP_URL="https://script.google.com/macros/s/$WEB_APP_ID/exec"
  save WEB_APP_ID; save WEB_APP_URL
  print "Web app: $WEB_APP_URL"
  # Re-push so issues copied from the template know the web app URL.
  write_deployment
  push
fi

VERSION=$(new_version "Deploy $(date -u +%Y-%m-%dT%H:%MZ)")
gj script projects deployments update --params "{\"scriptId\":\"$SCRIPT_ID\",\"deploymentId\":\"$WEB_APP_ID\"}" \
  --json "{\"deploymentConfig\":{\"versionNumber\":$VERSION,\"manifestFileName\":\"appsscript\",\"description\":\"Newsletter web version\"}}" \
  | field deploymentId >/dev/null
print "Web app now serves version $VERSION: $WEB_APP_URL"
