/**
 * Layout framework: design tokens + block templates for the newsletter HTML.
 *
 * DO NOT EDIT THIS FILE to restyle the newsletter - override tokens or
 * templates in Theme.js instead (see docs/THEMING.md). Keeping your changes
 * there means framework updates never overwrite them.
 *
 * Template syntax (a small Mustache subset):
 *   {{name}}             HTML-escaped value (dotted paths: {{t.width}}, {{c.accentColor}})
 *   {{{name}}}           raw value (pre-rendered HTML fragments, CSS)
 *   {{#name}}...{{/name}}  render if truthy; repeat for each item of an array
 *   {{^name}}...{{/name}}  render if falsy / empty
 * Line breaks and the indentation that follows them are removed, so templates
 * can be laid out readably. Keep any space you need on the same line.
 *
 * Every template also sees: t (tokens), c (settings/config), lang, rtl,
 * start ('left' or 'right'), pStyle (base paragraph style).
 */

var NL_DEFAULT_TOKENS = {
  // Card
  width: 700,                         // px; the email's max width
  pagePadding: '24px 10px 24px 10px', // around the card
  cardBackground: '#ffffff',
  cardRadius: '4px',
  cardBorder: '5px solid rgba(0,0,0,0.1)',

  // Type
  bodySize: 15,                       // px
  lineHeight: 1.5,
  h1Size: 26,
  h2Size: 20,
  h3Size: 17,
  headingLineHeight: 1.25,
  listIndent: '1.6em',

  // Spacing inside the card (CSS padding shorthand)
  h1Padding: '20px 20px 6px 20px',
  headingPadding: '14px 20px 4px 20px',
  richPadding: '5px 20px 20px 20px',
  dividerPadding: '20px 20px 20px 20px',
  imagePadding: '10px 20px 10px 20px',
  attachmentPadding: '10px 20px 10px 20px',
  tablePadding: '10px 20px 20px 20px',
  noticePadding: '14px 20px 0 20px',

  // Header band
  bannerPadding: '56px 24px 44px 24px',
  bannerTitleSize: 52,
  bannerTitleLineHeight: 1.05,
  subtitleSize: 17,
  subtitleSpacing: '0.08em',
  subtitleTransform: 'uppercase',
  subtitleColor: '#ffffff',

  // Divider
  dividerWidth: '2px',
  dividerStyle: 'solid',               // solid | dashed | dotted | double

  // Top bar ("View in browser" + languages)
  topBarBackground: '#f4f4f4',
  topBarBorder: '#dddddd',
  topBarText: '#777777',
  topBarLink: '#444444',

  // Download cards
  attachmentBorder: '#cccccc',
  attachmentRadius: '6px',

  // Tables
  tableBorder: '#dddddd',
  tableCellPadding: '8px',

  // Footer band and small print
  footerPadding: '16px 20px',
  footerNameSize: 18,
  footerTaglineSize: 13,
  footerLogoWidth: 52,
  footerNoteSize: 11,
  footerNoteColor: '#888888',

  // Machine-translation notice
  noticeBackground: '#fff8e1',
  noticeBorder: '#f0d58a',
  noticeText: '#5c4a12',

  // Phones
  mobileBreakpoint: 630,
  mobileGutter: '14px',
  mobileBodySize: 17,
  mobileH1Size: 24,
  mobileBannerTitleSize: 38
};

var NL_DEFAULT_TEMPLATES = {
  /* The whole message. Data: title, preheader, preheaderPad, css, bgStyle, topBar, notice, rows, footerNote */
  document: '<!DOCTYPE html>\n' +
    '<html lang="{{lang}}"{{#rtl}} dir="rtl"{{/rtl}} xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">\n' +
    '<head>\n' +
    '<meta charset="utf-8">\n' +
    '<meta name="viewport" content="width=device-width, initial-scale=1">\n' +
    '<meta http-equiv="X-UA-Compatible" content="IE=edge">\n' +
    '<meta name="x-apple-disable-message-reformatting">\n' +
    '<meta name="format-detection" content="telephone=no,address=no,email=no,date=no,url=no">\n' +
    '<meta name="color-scheme" content="light">\n' +
    '<meta name="supported-color-schemes" content="light">\n' +
    '<title>{{title}}</title>\n' +
    '<!--[if mso]><noscript><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml></noscript><![endif]-->\n' +
    '<style>{{{css}}}</style>\n' +
    '</head>\n' +
    '<body class="nl-body" style="margin:0;padding:0;width:100%;{{bgStyle}}">\n' +
    '<div style="display:none;font-size:1px;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;mso-hide:all;">{{preheader}}&nbsp;{{{preheaderPad}}}</div>\n' +
    '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="{{bgStyle}}">\n' +
    '{{{topBar}}}\n' +
    '<tr><td align="center" style="padding:{{t.pagePadding}};">\n' +
    '<!--[if mso]><table role="presentation" width="{{t.width}}" cellspacing="0" cellpadding="0" border="0"><tr><td><![endif]-->\n' +
    '<table role="presentation" class="nl-card" width="{{t.width}}" cellspacing="0" cellpadding="0" border="0" align="center" ' +
      'style="width:100%;max-width:{{t.width}}px;background:{{t.cardBackground}};border-radius:{{t.cardRadius}};border:{{t.cardBorder}};border-collapse:separate;">\n' +
    '{{{notice}}}\n' +
    '{{{rows}}}\n' +
    '</table>\n' +
    '<!--[if mso]></td></tr></table><![endif]-->\n' +
    '</td></tr>\n' +
    '{{#footerNote}}<tr><td align="center" style="padding:0 16px 24px 16px;font-family:Arial,sans-serif;font-size:{{t.footerNoteSize}}px;line-height:1.5;color:{{t.footerNoteColor}};">{{footerNote}}</td></tr>{{/footerNote}}\n' +
    '</table>\n' +
    '</body>\n' +
    '</html>',

  /* Data: view (url), hasLanguages, languages[{code, name, url, rtl, current, first}] */
  topBar: '<tr><td align="center" style="background:{{t.topBarBackground}};border-top:1px solid {{t.topBarBorder}};border-bottom:1px solid {{t.topBarBorder}};padding:8px 10px;">' +
    '<table role="presentation" class="nl-w" width="{{t.width}}" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:{{t.width}}px;">' +
    '{{#view}}<tr><td dir="ltr" style="font-family:Arial,sans-serif;font-size:12px;line-height:1.7;color:{{t.topBarText}};">Not displaying correctly? ' +
      '<a href="{{view}}" target="_blank" style="color:{{t.topBarLink}};text-decoration:underline;">View in browser</a></td></tr>{{/view}}' +
    '{{#hasLanguages}}<tr><td dir="ltr" style="font-family:Arial,sans-serif;font-size:12px;line-height:1.7;color:{{t.topBarText}};"><span aria-hidden="true">&#127760;</span> ' +
      '{{#languages}}{{^first}} &middot; {{/first}}' +
      '{{#current}}<strong lang="{{code}}"{{#rtl}} dir="rtl"{{/rtl}} style="color:#222222;">{{name}}</strong>{{/current}}' +
      '{{^current}}<a href="{{url}}" target="_blank" lang="{{code}}"{{#rtl}} dir="rtl"{{/rtl}} style="color:{{t.topBarLink}};text-decoration:underline;">{{name}}</a>{{/current}}' +
      '{{/languages}}</td></tr>{{/hasLanguages}}' +
    '</table></td></tr>',

  /* Translated pages only. Data: text (HTML), linkText (HTML), originalUrl */
  notice: '<tr><td class="nl-box" style="padding:{{t.noticePadding}};">' +
    '<div style="background:{{t.noticeBackground}};border:1px solid {{t.noticeBorder}};border-radius:4px;padding:10px 12px;font-family:{{c.bodyFont}};' +
    'font-size:13px;line-height:1.5;color:{{t.noticeText}};text-align:{{start}};">{{{text}}} ' +
    '<a href="{{originalUrl}}" style="color:{{c.linkColor}};font-weight:bold;">{{{linkText}}}</a></div></td></tr>',

  /* Text header band. Data: title (HTML), subtitle (HTML) */
  header: '<tr><td align="center" bgcolor="{{c.accentColor}}" style="background:{{c.accentColor}};border-radius:{{t.cardRadius}} {{t.cardRadius}} 0 0;padding:{{t.bannerPadding}};text-align:center;">' +
    '{{#title}}<h1 class="nl-banner-title" style="margin:0;font-family:{{c.headingFont}};font-size:{{t.bannerTitleSize}}px;line-height:{{t.bannerTitleLineHeight}};font-weight:bold;color:{{c.accentTextColor}};">{{{title}}}</h1>{{/title}}' +
    '{{#subtitle}}<p style="margin:18px 0 0 0;font-family:{{c.bodyFont}};font-size:{{t.subtitleSize}}px;letter-spacing:{{t.subtitleSpacing}};text-transform:{{t.subtitleTransform}};color:{{t.subtitleColor}};">{{{subtitle}}}</p>{{/subtitle}}' +
    '</td></tr>',

  /* Image placed above the Title in the Doc. Data: src, alt */
  bannerImage: '<tr><td style="background:{{c.accentColor}};border-radius:{{t.cardRadius}} {{t.cardRadius}} 0 0;" bgcolor="{{c.accentColor}}">' +
    '<img src="{{src}}" width="{{t.width}}" alt="{{alt}}" style="display:block;width:100%;max-width:{{t.width}}px;height:auto;border-radius:{{t.cardRadius}} {{t.cardRadius}} 0 0;"></td></tr>',

  /* Extension points: static rows right after the header / right before the footer. Empty by default. */
  cardTop: '',
  cardBottom: '',

  /* Heading 1-3. Data: level, tag (h2/h3/h4), isH1, size, padding, align, html */
  heading: '<tr><td class="nl-box" align="{{align}}" valign="top" style="padding:{{padding}};">' +
    '<{{tag}}{{#isH1}} class="nl-h1"{{/isH1}} style="margin:0;font-family:{{c.headingFont}};font-size:{{size}}px;line-height:{{t.headingLineHeight}};font-weight:bold;color:{{c.textColor}};text-align:{{align}};">' +
    '{{{html}}}</{{tag}}></td></tr>',

  /* Consecutive paragraphs and lists. Data: html */
  rich: '<tr><td class="nl-box" align="{{start}}" valign="top" style="padding:{{t.richPadding}};">' +
    '<div class="nl-rich" style="{{pStyle}}text-align:{{start}};">{{{html}}}</div></td></tr>',

  divider: '<tr><td class="nl-box" style="padding:{{t.dividerPadding}};">' +
    '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr>' +
    '<td style="border-top:{{t.dividerWidth}} {{t.dividerStyle}} {{c.accentColor}};font-size:1px;line-height:1px;height:1px;">&nbsp;</td></tr></table></td></tr>',

  /* Full-width image. Data: src, alt, href */
  image: '<tr><td align="center" valign="top">' +
    '{{#href}}<a href="{{href}}" target="_blank">{{/href}}' +
    '<img src="{{src}}" width="{{t.width}}" alt="{{alt}}" style="display:block;width:100%;max-width:{{t.width}}px;height:auto;">' +
    '{{#href}}</a>{{/href}}</td></tr>',

  /* Smaller image at its Doc size. Data: src, alt, href, width, height, align */
  imageSized: '<tr><td class="nl-box" align="{{align}}" valign="top" style="padding:{{t.imagePadding}};text-align:{{align}};">' +
    '{{#href}}<a href="{{href}}" target="_blank">{{/href}}' +
    '<img class="nl-img-sized" src="{{src}}" width="{{width}}"{{#height}} height="{{height}}"{{/height}} alt="{{alt}}" style="display:inline-block;width:{{width}}px;max-width:100%;height:auto;">' +
    '{{#href}}</a>{{/href}}</td></tr>',

  /* Download card. Data: href, kind (PDF...), kindSize, title (HTML), action (HTML), size */
  attachment: '<tr><td class="nl-box" style="padding:{{t.attachmentPadding}};">' +
    '<a href="{{href}}" target="_blank" style="text-decoration:none;color:{{c.textColor}};display:block;">' +
    '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="border:1px solid {{t.attachmentBorder}};border-radius:{{t.attachmentRadius}};border-collapse:separate;background:#ffffff;">' +
    '<tr><td width="52" valign="middle" style="padding:12px 0 12px 12px;">' +
    '<div style="width:40px;height:44px;line-height:44px;border-radius:4px;background:{{c.accentColor}};color:#ffffff;' +
    'font-family:Arial,sans-serif;font-size:{{kindSize}}px;font-weight:bold;text-align:center;">{{kind}}</div></td>' +
    '<td valign="middle" style="padding:12px;font-family:{{c.bodyFont}};font-size:{{t.bodySize}}px;line-height:1.4;font-weight:bold;color:{{c.textColor}};word-break:break-word;">' +
    '{{{title}}}</td>' +
    '<td width="90" align="center" valign="middle" style="padding:12px 12px 12px 0;font-family:{{c.bodyFont}};">' +
    '<div style="font-size:14px;font-weight:bold;color:{{c.linkColor}};text-decoration:underline;">{{{action}}}</div>' +
    '{{#size}}<div style="font-size:12px;color:#aaaaaa;">{{size}}</div>{{/size}}' +
    '</td></tr></table></a></td></tr>',

  /* Table wrapper; cells are built in code. Data: html */
  table: '<tr><td class="nl-box" style="padding:{{t.tablePadding}};">{{{html}}}</td></tr>',

  /* Footer band. Data: name, tagline, logoUrl */
  footer: '<tr><td bgcolor="{{c.accentColor}}" style="background:{{c.accentColor}};border-radius:0 0 {{t.cardRadius}} {{t.cardRadius}};padding:{{t.footerPadding}};">' +
    '<table role="presentation" cellspacing="0" cellpadding="0" border="0" style="margin:0!important;"><tr>' +
    '{{#logoUrl}}<td valign="middle" width="64" style="padding-right:12px;"><img src="{{logoUrl}}" width="{{t.footerLogoWidth}}" alt="{{name}}" style="display:block;"></td>{{/logoUrl}}' +
    '<td valign="middle" style="text-align:{{start}};">' +
    '{{#name}}<div style="font-family:{{c.bodyFont}};font-size:{{t.footerNameSize}}px;font-weight:bold;line-height:1.2;color:{{c.accentTextColor}};">{{name}}</div>{{/name}}' +
    '{{#tagline}}<div style="font-family:{{c.bodyFont}};font-size:{{t.footerTaglineSize}}px;line-height:1.4;color:{{c.accentTextColor}};">{{tagline}}</div>{{/tagline}}' +
    '</td></tr></table></td></tr>',

  /* <style> contents (raw CSS; keep critical styles inline in the templates above). */
  css: ':root{color-scheme:light;supported-color-schemes:light}' +
    'html,body{margin:0 auto!important;padding:0!important;width:100%!important}' +
    '*{-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}' +
    'table,td{mso-table-lspace:0pt!important;mso-table-rspace:0pt!important}' +
    'table{border-spacing:0!important;border-collapse:collapse;margin:0 auto}' +
    '.nl-card{table-layout:fixed}' +
    '.nl-rich a{word-break:break-all}' +
    'img{-ms-interpolation-mode:bicubic;border:0;outline:none;text-decoration:none}' +
    'a[x-apple-data-detectors],.unstyle-auto-detected-links a{border-bottom:0!important;cursor:default!important;color:inherit!important;text-decoration:none!important;font-size:inherit!important;font-family:inherit!important;font-weight:inherit!important;line-height:inherit!important}' +
    '.a6S{display:none!important;opacity:.01!important}' +
    'u + #body a{color:inherit;text-decoration:none;font-size:inherit;font-family:inherit;font-weight:inherit;line-height:inherit}' +
    '@media screen and (max-width:{{t.mobileBreakpoint}}px){' +
    '.nl-box{padding-left:{{t.mobileGutter}}!important;padding-right:{{t.mobileGutter}}!important}' +
    '.nl-rich p,.nl-rich li,.nl-rich span,.nl-rich td{font-size:{{t.mobileBodySize}}px!important}' +
    '.nl-h1{font-size:{{t.mobileH1Size}}px!important}' +
    '.nl-banner-title{font-size:{{t.mobileBannerTitleSize}}px!important}' +
    '.nl-img-sized{width:100%!important;height:auto!important}' +
    '.nl-card{border-width:0!important;border-radius:0!important}' +
    '}'
};

/* ------------------------------------------------------------------ */
/* Template engine                                                     */
/* ------------------------------------------------------------------ */

var NL_TPL_CACHE = {};
// {{{raw}}} or {{name}} / {{#name}} / {{^name}} / {{/name}}; a third brace only closes a triple.
var NL_TPL_TAG = /\{\{\{\s*([\w.]+)\s*\}\}\}|\{\{\s*([#^\/]?)\s*([\w.]+)\s*\}\}/g;

/** Compiles a template string into a node tree; throws on unbalanced sections. */
function nlCompileTpl(src) {
  if (NL_TPL_CACHE[src]) return NL_TPL_CACHE[src];
  var text = String(src).replace(/\n[ \t]*/g, '');
  var root = { children: [] };
  var stack = [root];
  var last = 0;
  var m;
  NL_TPL_TAG.lastIndex = 0;
  while ((m = NL_TPL_TAG.exec(text))) {
    var top = stack[stack.length - 1];
    if (m.index > last) top.children.push({ text: text.slice(last, m.index) });
    last = NL_TPL_TAG.lastIndex;
    var raw = m[1] !== undefined, op = raw ? '' : m[2], name = raw ? m[1] : m[3];
    if (op === '#' || op === '^') {
      var node = { section: name, inverted: op === '^', children: [] };
      top.children.push(node);
      stack.push(node);
    } else if (op === '/') {
      if (stack.length < 2 || top.section !== name) {
        throw new Error('Template section {{/' + name + '}} does not match ' + (top.section ? '{{#' + top.section + '}}' : 'any open section'));
      }
      stack.pop();
    } else {
      top.children.push({ name: name, raw: raw });
    }
  }
  if (stack.length > 1) throw new Error('Template section {{#' + stack[stack.length - 1].section + '}} is never closed');
  if (last < text.length) root.children.push({ text: text.slice(last) });
  NL_TPL_CACHE[src] = root;
  return root;
}

function nlTplLookup_(stack, name) {
  if (name === '.') return stack[stack.length - 1];
  var parts = name.split('.');
  for (var i = stack.length - 1; i >= 0; i--) {
    var ctx = stack[i];
    if (ctx !== null && typeof ctx === 'object' && parts[0] in ctx) {
      var v = ctx;
      for (var j = 0; j < parts.length && v != null; j++) v = v[parts[j]];
      return v;
    }
  }
  return undefined;
}

function nlTplRender_(nodes, stack, out) {
  nodes.forEach(function (n) {
    if (n.text !== undefined) { out.push(n.text); return; }
    var v = nlTplLookup_(stack, n.section || n.name);
    if (n.section) {
      var empty = !v || (Array.isArray(v) && !v.length);
      if (n.inverted) { if (empty) nlTplRender_(n.children, stack, out); return; }
      if (empty) return;
      if (Array.isArray(v)) {
        v.forEach(function (item) { nlTplRender_(n.children, stack.concat([item]), out); });
      } else {
        nlTplRender_(n.children, typeof v === 'object' ? stack.concat([v]) : stack, out);
      }
      return;
    }
    if (v === undefined || v === null || v === false) return;
    out.push(n.raw ? String(v) : nlEscTpl_(v));
  });
}

function nlEscTpl_(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

/** Renders a template string with the given data (objects are searched innermost-first). */
function nlTpl(src, data) {
  var out = [];
  nlTplRender_(nlCompileTpl(src).children, [data || {}], out);
  return out.join('');
}

/* ------------------------------------------------------------------ */
/* Themes                                                              */
/* ------------------------------------------------------------------ */

/** Defaults + theme overrides -> { tokens, templates }. Extra CSS is appended to the css template. */
function nlResolveLayout(theme) {
  theme = theme || {};
  var templates = Object.assign({}, NL_DEFAULT_TEMPLATES, theme.templates || {});
  if (theme.css) templates.css = templates.css + String(theme.css).replace(/\n[ \t]*/g, '');
  return {
    tokens: Object.assign({}, NL_DEFAULT_TOKENS, theme.tokens || {}),
    templates: templates
  };
}

/** Returns a list of problems with a theme (typos, unknown names, broken templates). */
function nlValidateTheme(theme) {
  var errors = [];
  if (!theme) return errors;
  Object.keys(theme).forEach(function (k) {
    if (['tokens', 'templates', 'css'].indexOf(k) < 0) errors.push('Unknown theme key "' + k + '" (use tokens, templates or css).');
  });
  Object.keys(theme.tokens || {}).forEach(function (k) {
    if (!(k in NL_DEFAULT_TOKENS)) errors.push('Unknown token "' + k + '".' + nlSuggest_(k, NL_DEFAULT_TOKENS));
    else if (typeof theme.tokens[k] !== typeof NL_DEFAULT_TOKENS[k]) {
      errors.push('Token "' + k + '" should be a ' + typeof NL_DEFAULT_TOKENS[k] + '.');
    }
  });
  Object.keys(theme.templates || {}).forEach(function (k) {
    if (!(k in NL_DEFAULT_TEMPLATES)) { errors.push('Unknown template "' + k + '".' + nlSuggest_(k, NL_DEFAULT_TEMPLATES)); return; }
    if (typeof theme.templates[k] !== 'string') { errors.push('Template "' + k + '" must be a string.'); return; }
    try { nlCompileTpl(theme.templates[k]); } catch (e) { errors.push('Template "' + k + '": ' + e.message); }
  });
  if (theme.css !== undefined && typeof theme.css !== 'string') errors.push('css must be a string.');
  return errors;
}

/** Closest known name within two edits (typos like "h1Szie"), as a hint. */
function nlSuggest_(name, known) {
  var best = null, bestDist = 3;
  Object.keys(known).forEach(function (k) {
    var d = nlEditDistance_(name.toLowerCase(), k.toLowerCase());
    if (d < bestDist) { best = k; bestDist = d; }
  });
  return best ? ' Did you mean "' + best + '"?' : '';
}

/** Optimal string alignment distance: insert, delete, substitute, swap adjacent letters. */
function nlEditDistance_(a, b) {
  var d = [];
  for (var i = 0; i <= a.length; i++) { d[i] = [i]; }
  for (var j = 1; j <= b.length; j++) d[0][j] = j;
  for (i = 1; i <= a.length; i++) {
    for (j = 1; j <= b.length; j++) {
      var cost = a[i - 1] === b[j - 1] ? 0 : 1;
      d[i][j] = Math.min(d[i - 1][j] + 1, d[i][j - 1] + 1, d[i - 1][j - 1] + cost);
      if (i > 1 && j > 1 && a[i - 1] === b[j - 2] && a[i - 2] === b[j - 1]) d[i][j] = Math.min(d[i][j], d[i - 2][j - 2] + 1);
    }
  }
  return d[a.length][b.length];
}

var NL_LAYOUT_API = {
  tpl: nlTpl,
  resolve: nlResolveLayout,
  validate: nlValidateTheme,
  tokens: NL_DEFAULT_TOKENS,
  templates: NL_DEFAULT_TEMPLATES
};

if (typeof module !== 'undefined') {
  module.exports = {
    NL_LAYOUT_API: NL_LAYOUT_API,
    NL_DEFAULT_TOKENS: NL_DEFAULT_TOKENS,
    NL_DEFAULT_TEMPLATES: NL_DEFAULT_TEMPLATES,
    nlTpl: nlTpl,
    nlCompileTpl: nlCompileTpl,
    nlResolveLayout: nlResolveLayout,
    nlValidateTheme: nlValidateTheme
  };
}
