/**
 * Email-look web version ("View in browser").
 *
 * "Publish web version" writes the rendered email to an HTML snapshot in a
 * private Drive folder. The template's script is deployed once as a public web
 * app; doGet serves ?issue=<snapshot file id>, and only files inside that folder.
 *
 * NEWSLETTER_DEPLOYMENT comes from Deployment.js, generated by
 * scripts/deploy-script.zsh. Copies of the template inherit it, so every issue
 * links to the same web app.
 */

var NL_SNAPSHOT_KEY = 'snapshotFileId';

function nlDeployment_() {
  return typeof NEWSLETTER_DEPLOYMENT !== 'undefined' && NEWSLETTER_DEPLOYMENT.webAppUrl &&
    NEWSLETTER_DEPLOYMENT.snapshotFolderId ? NEWSLETTER_DEPLOYMENT : null;
}

function doGet(e) {
  var dep = nlDeployment_();
  var id = e && e.parameter && e.parameter.issue;
  var file = dep && id && /^[\w-]{10,100}$/.test(id) ? nlSnapshotFile_(id, dep.snapshotFolderId) : null;
  if (!file) {
    return HtmlService.createHtmlOutput(
      '<p style="font-family:Arial,sans-serif;padding:24px;color:#444">This newsletter could not be found.</p>')
      .setTitle('Newsletter not found');
  }
  return HtmlService.createHtmlOutput(file.getBlob().getDataAsString())
    .setTitle(file.getDescription() || file.getName().replace(/\.html$/, ''))
    .addMetaTag('viewport', 'width=device-width, initial-scale=1');
}

/** Returns the snapshot only if it is an HTML file directly inside the snapshot folder. */
function nlSnapshotFile_(id, folderId) {
  try {
    var file = DriveApp.getFileById(id);
    if (file.getMimeType() !== MimeType.HTML) return null;
    var parents = file.getParents();
    while (parents.hasNext()) {
      if (parents.next().getId() === folderId) return file;
    }
  } catch (err) { /* missing or not ours */ }
  return null;
}

/** The snapshot for the active Doc, or null if it was never published. */
function nlExistingSnapshot_() {
  var dep = nlDeployment_();
  var id = PropertiesService.getDocumentProperties().getProperty(NL_SNAPSHOT_KEY);
  return dep && id ? nlSnapshotFile_(id, dep.snapshotFolderId) : null;
}

/** Creates (or reuses) this issue's snapshot file so its URL is known before rendering. */
function nlEnsureSnapshot_(name) {
  var existing = nlExistingSnapshot_();
  if (existing) return existing;
  var folder = DriveApp.getFolderById(nlDeployment_().snapshotFolderId);
  var file = folder.createFile(name.replace(/[\\/]/g, '-') + '.html', '<!DOCTYPE html><title>Publishing…</title>', MimeType.HTML);
  PropertiesService.getDocumentProperties().setProperty(NL_SNAPSHOT_KEY, file.getId());
  return file;
}

function nlSnapshotUrl_(file) {
  return nlDeployment_().webAppUrl + '?issue=' + encodeURIComponent(file.getId());
}

function nlWriteSnapshot_(file, html, subject) {
  file.setContent(html);
  file.setDescription(subject);
}

if (typeof module !== 'undefined') module.exports = { doGet: doGet };
